name: blinkit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  # Pin to 10.7.0 to avoid using newer Color.withValues/a APIs
  font_awesome_flutter: 10.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
      - assets/products/
      - assets/banner_img.png
      - assets/promo1.png
      - assets/promo2.png
      - assets/promo3.png
      - assets/burger.jpeg
      - assets/products/care/care1.png
      - assets/products/care/care2.png
      - assets/products/care/care3.png
      - assets/products/care/care4.png
      - assets/products/care/care5.png
      - assets/products/care/care6.png
      - assets/products/Grocery/grocery1.png
      - assets/products/Grocery/grocery2.png
      - assets/products/Grocery/grocery3.png
      - assets/products/Grocery/grocery4.png
      - assets/products/Grocery/grocery5.png
      - assets/products/Grocery/grocery6.png
      - assets/products/homecare/homecare1.png
      - assets/products/homecare/homecare2.png
      - assets/products/homecare/homecare3.png
      - assets/products/homecare/homecare4.png
      - assets/products/snacks/snacks1.png
      - assets/products/snacks/snacks2.png
      - assets/products/snacks/snacks3.png
      - assets/products/snacks/snacks4.png
      - assets/products/snacks/snacks5.png
      - assets/products/snacks/snacks6.png
     
     
